---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: blat6

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
